main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
  path('', views.shop, name='shop'),
  path('category/<str:cat>/', views.category, name='category'),
  path('item/<int:pk>', views.ItemDetail.as_view(), name='item_detail'),
  path('manage/', include('main_app.manage_urls')),
  path('accounts/signup/', views.signup, name='signup'),
]

sadfood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
  name = models.CharField(max_length=50)

  def __str__(self):
    return self.name

class Item(models.Model):
  FINISH = (
    ('P', 'Just Plush'),
    ('K', 'Keychain'),
    ('O', 'Ornament'),
  )
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  materials = models.CharField(max_length=100)
  price = models.DecimalField(max_digits=10, decimal_places=2)
  finish = models.CharField(
    max_length=1,
    choices=FINISH,
    default=FINISH[0][0]
  )
  dimensions = models.CharField(max_length=50)
  categories = models.ManyToManyField(Category)

  def get_absolute_url(self):
    return reverse('item_detail', kwargs={'pk': self.id})

  def __str__(self):
      return self.name
  

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  favorites = models.ManyToManyField(Item)

  def __str__(self):
    return self.user.username
  
class Photo(models.Model):
  url = models.CharField(max_length=200)
  item = models.ForeignKey(Item, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for item_id: {self.item_id} @{self.url}"

main_app/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from .models import Item, Category, Profile

def home(request):
  return render(request, 'home.html')

def shop(request):
  items = Item.objects.all()
  categories = Category.objects.all()
  return render(request, 'shop.html', {
    'items': items, 'catlist': categories})

class ItemDetail(DetailView):
  model = Item

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['catlist'] = Category.objects.all()
    return context

def category(request, cat):
  categories = Category.objects.all()
  cat_items = Item.objects.filter(categories__name__iexact=cat)
  return render(request, 'shop.html', {
    'category': cat, 'items': cat_items, 'catlist': categories})

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      profile = Profile(user=user)
      profile.save()
      login(request, user)
      return redirect('shop')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>SadFood Toys</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <nav>
    <ul>
      <li><a href='{% url 'shop' %}'>Shop</a></li>
    </ul>
    <ul class='right'>
      {% if user.is_authenticated %}
      <li><a href="{% url 'logout' %}">Log Out ({{user}})</a></li>
      {% else %}
      <li><a href="{% url 'signup' %}">Sign Up</a></li>
      <li><a href="{% url 'login' %}">Log In</a></li>
      {% endif %}
    </ul>
  </nav>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <footer>
  &copy; Copyright 2021 Sean Niles
  </footer>
</body>
</html>

main_app/templates/category_nav.html
<aside>
  <h2>Categories</h2>
  <ul>
    <li><a href='{% url 'shop' %}'>All</a></li>

    {% for cat in catlist %}
    <li><a href='{% url 'category' cat|lower %}'>{{cat}}</a></li>
    {% endfor %}
  </ul>
</aside>

main_app/templates/form_snippet.html
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/item_card.html
<div class='item-card'>
  <div class='item-photo'>
    <a href='{% url "item_detail" item.id %}'>
    {% comment %} <img src='https://picsum.photos/200' /> {% endcomment %}
    {% for photo in item.photo_set.all %}
      <img src="{{photo.url}}" />
    {% empty %}
      <p>No photo uploaded</p>
    {% endfor %}
    </a>
  </div>
  <div class='item-info'>
    <a href='{% url "item_detail" item.id %}'>
      <span class='name'>{{item.name}}</span>
    </a>
    <span>${{item.price}}</span>
    <span>{{item.description}}</span>
  </div>
</div>

main_app/templates/main_app/category_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
{% include 'manage_nav.html' %}
<article>
  <div class="center">
  <h1>Delete Category</h1>

  <h4>Are you sure you want to delete {{ object }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
  </form>
  </div>
</article>
{% endblock %}

main_app/templates/main_app/category_form.html
{% extends 'base.html' %}

{% block content %}  
{% include 'manage_nav.html' %}
<article>
  <div class="center">
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Category</h1>
  {% endif %}
  
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn">
  </form>
  {% if object %}
    <a href="{% url 'category_delete' object.id %}" class='delete-btn'>Delete Category</a>
  {% endif %}
  </div>
</article>

{% endblock %}

main_app/templates/main_app/category_list.html
{% extends 'base.html' %}
{% block content %}
{% include 'manage_nav.html' %}

<article>
<h1>Category List</h1>
  <div class="center">
  {% for category in category_list %}
    <p><a href="{% url 'category_update' category.id %}">{{category}}</a></p>
  {% endfor %}
  </center>
</article>

{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
{% include 'manage_nav.html' %}
<article>
  <div class="center">
  <h1>Delete Item</h1>

  <h4>Are you sure you want to delete {{ object }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
  </form>
  </div>
</article>
{% endblock %}

main_app/templates/main_app/item_detail.html
{% extends 'base.html' %}
{% block content %}

{% include 'category_nav.html' %}
<article>
  <h1>{{object.name}}</h1>
  <div class='two-cols'>
    <div class='col-one'>
      {% for photo in object.photo_set.all %}
        <img src="{{photo.url}}" class='item-detail-photo' />
      {% empty %}
        <p>No photo uploaded</p>
      {% endfor %}
    </div>
    <div class='col-two'>
      <p><strong>Description: </strong>{{object.description}}</p>
      <p><strong>Materials: </strong>{{object.materials}}</p>
      <p><strong>Price: </strong>${{object.price}}</p>
      <p><strong>Finish: </strong>{{object.get_finish_display}}</p>
      <p><strong>Dimensions: </strong>{{object.dimensions}}</p>
      <p><strong>Categories: </strong>
      {% for cat in object.categories.all %}
        <p>{{cat}}</p>
      {% endfor %}
      </p>
    </div>
  </div>
</article>
{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}
{% block content %}
{% include 'manage_nav.html' %}

<article>
  <div class='center'>
  {% if object %}
    <h1>Edit {{object.name}}</h1>
  {% else %}
    <h1>Add Item</h1>
  {% endif %}
  
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn">
  </form>
  {% if object %}
    <a href="{% url 'item_delete' object.id %}" class='delete-btn'>Delete Item</a>
    <hr />
    <h1>Photos</h1>
    {% for photo in item.photo_set.all %}
      <img src="{{photo.url}}" class='item-detail-photo' />
    {% empty %}
      <p>No photo uploaded</p>
    {% endfor %}
    <h1>Add Photo</h1>
    <form action="{% url 'add_photo' object.id %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <input type="submit" class="btn" value="Upload Photo">
</form>
  {% endif %}
  <div class='center'>
</article>
{% endblock %}

main_app/templates/main_app/item_list.html
{% extends 'base.html' %}
{% block content %}

{% include 'manage_nav.html' %}
<article>
  <div class='center'>
  <h1>Item List</h1>
    <div class='center'>

  {% for item in item_list %}
    <p>
      <a href="{% url 'item_update' item.id %}">
        {{ item.name }}
      </a>
    </p>
  {% endfor %}
    </div>
  </div>
</article>
{% endblock %}

main_app/templates/manage_nav.html
<aside>
  <h2>Manage Shop</h2>
  
  <ul>
    <li><a href='{% url "item_list" %}'>Item List</a></li>
    <li><a href='{% url "item_create" %}'>Create Item</a></li>
    <li class='li-spacer'>-</li>
    <li><a href='{% url "category_list" %}'>Category List</a></li>
    <li><a href='{% url "category_create" %}'>Create Category</a></li>
</aside>

main_app/templates/shop.html
{% extends 'base.html' %}
{% block content %}

{% include 'category_nav.html' %}
<article>
  <h1>{{ category|title|default:'Shop' }}</h1>
  <div class='cardwrap'>
  {% for item in items %}
    {% include 'item_card.html' %}

    {% comment %} {% for category in item.categories.all %}
      {{category}}
    {% endfor%} {% endcomment %}
  {% endfor %}
  </div>
</article>
{% endblock %}